#!/usr/bin/env python
# encoding: utf-8
# Qball Cow, 2008 


obj=bld.create_obj('intltool_in')
obj.source  = 'stuffkeeper.desktop.in'
obj.destvar = 'PREFIX'
obj.subdir  = '/share/applications/'
obj.podir   = '../po'
obj.flags   = '-d'

