/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __STUFFKEEPER_DATA_ITEM_PRIVATE_H__
#define __STUFFKEEPER_DATA_ITEM_PRIVATE_H__

#include "stuffkeeper-data-item.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 3 "stuffkeeper-data-item.gob"

    #include "stuffkeeper-data-backend.h"

#line 18 "stuffkeeper-data-item-private.h"
struct _StuffKeeperDataItemPrivate {
#line 15 "stuffkeeper-data-item.gob"
	gint id;
#line 16 "stuffkeeper-data-item.gob"
	gchar * title;
#line 24 "stuffkeeper-data-item-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
