/* Generated by GOB (v2.0.14)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 14

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "stuffkeeper-data-tag.h"

#include "stuffkeeper-data-tag-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) STUFFKEEPER_DATA_TAG(x)
#define SELF_CONST(x) STUFFKEEPER_DATA_TAG_CONST(x)
#define IS_SELF(x) STUFFKEEPER_IS_DATA_TAG(x)
#define TYPE_SELF STUFFKEEPER_TYPE_DATA_TAG
#define SELF_CLASS(x) STUFFKEEPER_DATA_TAG_CLASS(x)

#define SELF_GET_CLASS(x) STUFFKEEPER_DATA_TAG_GET_CLASS(x)

/* self typedefs */
typedef StuffKeeperDataTag Self;
typedef StuffKeeperDataTagClass SelfClass;

/* here are local prototypes */
static void stuffkeeper_data_tag_init (StuffKeeperDataTag * o) G_GNUC_UNUSED;
static void stuffkeeper_data_tag_class_init (StuffKeeperDataTagClass * c) G_GNUC_UNUSED;
static void ___real_stuffkeeper_data_tag_tag_changed (StuffKeeperDataTag * self);

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__tag_changed(object,func,data)	stuffkeeper_data_tag_connect__tag_changed((object),(func),(data))
#define self_connect_after__tag_changed(object,func,data)	stuffkeeper_data_tag_connect_after__tag_changed((object),(func),(data))
#define self_connect_data__tag_changed(object,func,data,destroy_data,flags)	stuffkeeper_data_tag_connect_data__tag_changed((object),(func),(data),(destroy_data),(flags))

enum {
	TAG_CHANGED_SIGNAL,
	LAST_SIGNAL
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_tag_changed stuffkeeper_data_tag_tag_changed
#define self_new_from_file stuffkeeper_data_tag_new_from_file
#define self_new_with_id stuffkeeper_data_tag_new_with_id
#define self_new stuffkeeper_data_tag_new
#define self_get_id stuffkeeper_data_tag_get_id
#define self_get_title stuffkeeper_data_tag_get_title
#define self_set_title stuffkeeper_data_tag_set_title
#define self_save_yourself stuffkeeper_data_tag_save_yourself
#define self_delete_yourself stuffkeeper_data_tag_delete_yourself
GType
stuffkeeper_data_tag_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (StuffKeeperDataTagClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) stuffkeeper_data_tag_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (StuffKeeperDataTag),
			0 /* n_preallocs */,
			(GInstanceInitFunc) stuffkeeper_data_tag_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "StuffKeeperDataTag", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((StuffKeeperDataTag *)g_object_new(stuffkeeper_data_tag_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static StuffKeeperDataTag * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static StuffKeeperDataTag *
GET_NEW_VARG (const char *first, ...)
{
	StuffKeeperDataTag *ret;
	va_list ap;
	va_start (ap, first);
	ret = (StuffKeeperDataTag *)g_object_new_valist (stuffkeeper_data_tag_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::finalize"
	StuffKeeperDataTag *self G_GNUC_UNUSED = STUFFKEEPER_DATA_TAG (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 12 "stuffkeeper-data-tag.gob"
	if(self->_priv->path) { g_free ((gpointer) self->_priv->path); self->_priv->path = NULL; }
#line 123 "stuffkeeper-data-tag.c"
}
#undef __GOB_FUNCTION__

static void 
stuffkeeper_data_tag_init (StuffKeeperDataTag * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::init"
	o->_priv = G_TYPE_INSTANCE_GET_PRIVATE(o,STUFFKEEPER_TYPE_DATA_TAG,StuffKeeperDataTagPrivate);
#line 11 "stuffkeeper-data-tag.gob"
	o->_priv->data = NULL;
#line 134 "stuffkeeper-data-tag.c"
#line 12 "stuffkeeper-data-tag.gob"
	o->_priv->path = NULL;
#line 137 "stuffkeeper-data-tag.c"
}
#undef __GOB_FUNCTION__
static void 
stuffkeeper_data_tag_class_init (StuffKeeperDataTagClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	g_type_class_add_private(c,sizeof(StuffKeeperDataTagPrivate));

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	object_signals[TAG_CHANGED_SIGNAL] =
		g_signal_new ("tag_changed",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (StuffKeeperDataTagClass, tag_changed),
			NULL, NULL,
			g_cclosure_marshal_VOID__VOID,
			G_TYPE_NONE, 0);

#line 18 "stuffkeeper-data-tag.gob"
	c->tag_changed = ___real_stuffkeeper_data_tag_tag_changed;
#line 161 "stuffkeeper-data-tag.c"
	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__



#line 18 "stuffkeeper-data-tag.gob"
void 
stuffkeeper_data_tag_tag_changed (StuffKeeperDataTag * self)
#line 171 "stuffkeeper-data-tag.c"
{
	GValue ___param_values[1];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 18 "stuffkeeper-data-tag.gob"
	g_return_if_fail (self != NULL);
#line 18 "stuffkeeper-data-tag.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_TAG (self));
#line 183 "stuffkeeper-data-tag.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	g_signal_emitv (___param_values,
		object_signals[TAG_CHANGED_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
}
#line 18 "stuffkeeper-data-tag.gob"
static void 
___real_stuffkeeper_data_tag_tag_changed (StuffKeeperDataTag * self G_GNUC_UNUSED)
#line 199 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::tag_changed"
{
#line 21 "stuffkeeper-data-tag.gob"
	
            gint id = self_get_id(self);
            printf("Signal my tag change : %i\n", id); 
        }}
#line 208 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__

#line 26 "stuffkeeper-data-tag.gob"
StuffKeeperDataTag * 
stuffkeeper_data_tag_new_from_file (const gchar * file)
#line 214 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::new_from_file"
{
#line 29 "stuffkeeper-data-tag.gob"
	
            Self *obj = GET_NEW;
            obj->_priv->data = g_key_file_new();
            obj->_priv->path = g_strdup(file);
            g_key_file_load_from_file(obj->_priv->data, obj->_priv->path, G_KEY_FILE_KEEP_COMMENTS, NULL);

            return obj;
        }}
#line 227 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__

#line 38 "stuffkeeper-data-tag.gob"
StuffKeeperDataTag * 
stuffkeeper_data_tag_new_with_id (const gchar * path, gint id)
#line 233 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::new_with_id"
{
#line 41 "stuffkeeper-data-tag.gob"
	
            Self *obj = GET_NEW;
            obj->_priv->path = g_strdup_printf("%s%c%i", path, G_DIR_SEPARATOR,id);
            obj->_priv->data = g_key_file_new();
            g_key_file_set_integer(obj->_priv->data, KEYFILE_GENERAL,"id", id);
            printf("Creating tag: %i\n", id);
            self_save_yourself(obj);
            return obj;
        }}
#line 247 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__

#line 52 "stuffkeeper-data-tag.gob"
StuffKeeperDataTag * 
stuffkeeper_data_tag_new (const gchar * path)
#line 253 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::new"
{
#line 55 "stuffkeeper-data-tag.gob"
	

            Self *obj = GET_NEW;
            gint id = g_random_int();
            obj->_priv->path = g_strdup_printf("%s%c%i", path, G_DIR_SEPARATOR,id);
            obj->_priv->data = g_key_file_new();
            g_key_file_set_integer(obj->_priv->data, KEYFILE_GENERAL,"id", id);
            printf("Creating tag: %i\n", id);
            self_save_yourself(obj);
            return obj;
        }}
#line 269 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__

#line 70 "stuffkeeper-data-tag.gob"
gint 
stuffkeeper_data_tag_get_id (StuffKeeperDataTag * self)
#line 275 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::get_id"
#line 70 "stuffkeeper-data-tag.gob"
	g_return_val_if_fail (self != NULL, (gint )0);
#line 70 "stuffkeeper-data-tag.gob"
	g_return_val_if_fail (STUFFKEEPER_IS_DATA_TAG (self), (gint )0);
#line 282 "stuffkeeper-data-tag.c"
{
#line 73 "stuffkeeper-data-tag.gob"
	
            gint id = g_key_file_get_integer(self->_priv->data, KEYFILE_GENERAL, "id",NULL);
            return id;
        }}
#line 289 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__

#line 81 "stuffkeeper-data-tag.gob"
gchar * 
stuffkeeper_data_tag_get_title (StuffKeeperDataTag * self)
#line 295 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::get_title"
#line 81 "stuffkeeper-data-tag.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 81 "stuffkeeper-data-tag.gob"
	g_return_val_if_fail (STUFFKEEPER_IS_DATA_TAG (self), (gchar * )0);
#line 302 "stuffkeeper-data-tag.c"
{
#line 84 "stuffkeeper-data-tag.gob"
	
        return g_key_file_get_string(self->_priv->data, KEYFILE_GENERAL, "title", NULL); 
    }}
#line 308 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__

#line 89 "stuffkeeper-data-tag.gob"
void 
stuffkeeper_data_tag_set_title (StuffKeeperDataTag * self, const gchar * title)
#line 314 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::set_title"
#line 89 "stuffkeeper-data-tag.gob"
	g_return_if_fail (self != NULL);
#line 89 "stuffkeeper-data-tag.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_TAG (self));
#line 321 "stuffkeeper-data-tag.c"
{
#line 92 "stuffkeeper-data-tag.gob"
	
        g_key_file_set_string(self->_priv->data, KEYFILE_GENERAL, "title", title);
        printf("new title: %s\n", title);
        self_tag_changed(self);
    }}
#line 329 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__

#line 118 "stuffkeeper-data-tag.gob"
void 
stuffkeeper_data_tag_save_yourself (StuffKeeperDataTag * self)
#line 335 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::save_yourself"
#line 118 "stuffkeeper-data-tag.gob"
	g_return_if_fail (self != NULL);
#line 118 "stuffkeeper-data-tag.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_TAG (self));
#line 342 "stuffkeeper-data-tag.c"
{
#line 121 "stuffkeeper-data-tag.gob"
	
            gint id = self_get_id(self);
            printf("saving myself: %i\n",id);
            if(self->_priv->data)
            {
                char *content;
                gsize size;
                content = g_key_file_to_data(self->_priv->data,&size, NULL);
                g_file_set_contents(self->_priv->path, content, size, NULL);
                g_free(content);
            }
        }}
#line 357 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__

#line 134 "stuffkeeper-data-tag.gob"
void 
stuffkeeper_data_tag_delete_yourself (StuffKeeperDataTag * self)
#line 363 "stuffkeeper-data-tag.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Tag::delete_yourself"
#line 134 "stuffkeeper-data-tag.gob"
	g_return_if_fail (self != NULL);
#line 134 "stuffkeeper-data-tag.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_TAG (self));
#line 370 "stuffkeeper-data-tag.c"
{
#line 137 "stuffkeeper-data-tag.gob"
	
            gint id = self_get_id(self);
            printf("Deleting myself: %i\n", id);
            g_key_file_set_integer(self->_priv->data, KEYFILE_GENERAL,"id", -1);
            g_unlink(self->_priv->path);
            g_free(self->_priv->path);
            self->_priv->path = NULL;
        }}
#line 381 "stuffkeeper-data-tag.c"
#undef __GOB_FUNCTION__
