/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __STUFFKEEPER_DATA_ITEM_PRIVATE_H__
#define __STUFFKEEPER_DATA_ITEM_PRIVATE_H__

#include "stuffkeeper-data-item.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 3 "stuffkeeper-data-item.gob"


#define KEYFILE_GENERAL "general"
#define KEYFILE_CUSTOM "custom"

#line 20 "stuffkeeper-data-item-private.h"

#line 9 "stuffkeeper-data-item.gob"

    #include "stuffkeeper-data-backend.h"

#line 26 "stuffkeeper-data-item-private.h"
struct _StuffKeeperDataItemPrivate {
#line 20 "stuffkeeper-data-item.gob"
	StuffKeeperDataBackend * skdb;
#line 21 "stuffkeeper-data-item.gob"
	GKeyFile * data;
#line 22 "stuffkeeper-data-item.gob"
	char * path;
#line 23 "stuffkeeper-data-item.gob"
	GList * tags;
#line 36 "stuffkeeper-data-item-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
