/* Generated by GOB (v2.0.14)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 14

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "stuffkeeper-data-backend.h"

#include "stuffkeeper-data-backend-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) STUFFKEEPER_DATA_BACKEND(x)
#define SELF_CONST(x) STUFFKEEPER_DATA_BACKEND_CONST(x)
#define IS_SELF(x) STUFFKEEPER_IS_DATA_BACKEND(x)
#define TYPE_SELF STUFFKEEPER_TYPE_DATA_BACKEND
#define SELF_CLASS(x) STUFFKEEPER_DATA_BACKEND_CLASS(x)

#define SELF_GET_CLASS(x) STUFFKEEPER_DATA_BACKEND_GET_CLASS(x)

/* self typedefs */
typedef StuffKeeperDataBackend Self;
typedef StuffKeeperDataBackendClass SelfClass;

/* here are local prototypes */
static void stuffkeeper_data_backend_init (StuffKeeperDataBackend * o) G_GNUC_UNUSED;
static void stuffkeeper_data_backend_class_init (StuffKeeperDataBackendClass * c) G_GNUC_UNUSED;
static void ___real_stuffkeeper_data_backend_item_changed (StuffKeeperDataBackend * self, StuffKeeperDataItem * item);
static void ___real_stuffkeeper_data_backend_item_added (StuffKeeperDataBackend * self, StuffKeeperDataItem * item);
static void ___real_stuffkeeper_data_backend_item_removed (StuffKeeperDataBackend * self, gint id);
static void stuffkeeper_data_backend_finalize_item (gint * key, StuffKeeperDataItem * item, gpointer user_data) G_GNUC_UNUSED;
static void ___9_stuffkeeper_data_backend_finalize (GObject * obj) G_GNUC_UNUSED;

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__item_changed(object,func,data)	stuffkeeper_data_backend_connect__item_changed((object),(func),(data))
#define self_connect_after__item_changed(object,func,data)	stuffkeeper_data_backend_connect_after__item_changed((object),(func),(data))
#define self_connect_data__item_changed(object,func,data,destroy_data,flags)	stuffkeeper_data_backend_connect_data__item_changed((object),(func),(data),(destroy_data),(flags))
#define self_connect__item_added(object,func,data)	stuffkeeper_data_backend_connect__item_added((object),(func),(data))
#define self_connect_after__item_added(object,func,data)	stuffkeeper_data_backend_connect_after__item_added((object),(func),(data))
#define self_connect_data__item_added(object,func,data,destroy_data,flags)	stuffkeeper_data_backend_connect_data__item_added((object),(func),(data),(destroy_data),(flags))
#define self_connect__item_removed(object,func,data)	stuffkeeper_data_backend_connect__item_removed((object),(func),(data))
#define self_connect_after__item_removed(object,func,data)	stuffkeeper_data_backend_connect_after__item_removed((object),(func),(data))
#define self_connect_data__item_removed(object,func,data,destroy_data,flags)	stuffkeeper_data_backend_connect_data__item_removed((object),(func),(data),(destroy_data),(flags))

typedef void  (*___Sig1) (StuffKeeperDataBackend *, gpointer , gpointer);

static void
___marshal_Sig1 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	register ___Sig1 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 2);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig1) (marshal_data != NULL ? marshal_data : cc->callback);

	callback ((StuffKeeperDataBackend *)data1,
		(gpointer ) g_value_get_pointer (param_values + 1),
		data2);
}


typedef void  (*___Sig2) (StuffKeeperDataBackend *, gint , gpointer);

static void
___marshal_Sig2 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	register ___Sig2 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 2);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig2) (marshal_data != NULL ? marshal_data : cc->callback);

	callback ((StuffKeeperDataBackend *)data1,
		(gint ) g_value_get_int (param_values + 1),
		data2);
}


enum {
	ITEM_CHANGED_SIGNAL,
	ITEM_ADDED_SIGNAL,
	ITEM_REMOVED_SIGNAL,
	LAST_SIGNAL
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_item_changed stuffkeeper_data_backend_item_changed
#define self_item_added stuffkeeper_data_backend_item_added
#define self_item_removed stuffkeeper_data_backend_item_removed
#define self_get_item stuffkeeper_data_backend_get_item
#define self_new_item stuffkeeper_data_backend_new_item
#define self_remove_item stuffkeeper_data_backend_remove_item
#define self_load stuffkeeper_data_backend_load
#define self_finalize_item stuffkeeper_data_backend_finalize_item
#define self_new stuffkeeper_data_backend_new
GType
stuffkeeper_data_backend_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (StuffKeeperDataBackendClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) stuffkeeper_data_backend_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (StuffKeeperDataBackend),
			0 /* n_preallocs */,
			(GInstanceInitFunc) stuffkeeper_data_backend_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "StuffKeeperDataBackend", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((StuffKeeperDataBackend *)g_object_new(stuffkeeper_data_backend_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static StuffKeeperDataBackend * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static StuffKeeperDataBackend *
GET_NEW_VARG (const char *first, ...)
{
	StuffKeeperDataBackend *ret;
	va_list ap;
	va_start (ap, first);
	ret = (StuffKeeperDataBackend *)g_object_new_valist (stuffkeeper_data_backend_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::finalize"
	StuffKeeperDataBackend *self G_GNUC_UNUSED = STUFFKEEPER_DATA_BACKEND (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
#line 129 "stuffkeeper-data-backend.gob"
	___9_stuffkeeper_data_backend_finalize(obj_self);
#line 197 "stuffkeeper-data-backend.c"
}
#undef __GOB_FUNCTION__

static void 
stuffkeeper_data_backend_init (StuffKeeperDataBackend * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::init"
	o->_priv = G_TYPE_INSTANCE_GET_PRIVATE(o,STUFFKEEPER_TYPE_DATA_BACKEND,StuffKeeperDataBackendPrivate);
#line 13 "stuffkeeper-data-backend.gob"
	o->_priv->items = g_hash_table_new_full(g_int_hash, g_int_equal,g_free, g_object_unref);
#line 208 "stuffkeeper-data-backend.c"
}
#undef __GOB_FUNCTION__
static void 
stuffkeeper_data_backend_class_init (StuffKeeperDataBackendClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	g_type_class_add_private(c,sizeof(StuffKeeperDataBackendPrivate));

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	object_signals[ITEM_CHANGED_SIGNAL] =
		g_signal_new ("item_changed",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (StuffKeeperDataBackendClass, item_changed),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_NONE, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(StuffKeeperDataItem * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("stuffkeeper-data-backend.gob line 18: Type mismatch of \"item_changed\" signal signature");
	}
	object_signals[ITEM_ADDED_SIGNAL] =
		g_signal_new ("item_added",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (StuffKeeperDataBackendClass, item_added),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_NONE, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(StuffKeeperDataItem * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("stuffkeeper-data-backend.gob line 25: Type mismatch of \"item_added\" signal signature");
	}
	object_signals[ITEM_REMOVED_SIGNAL] =
		g_signal_new ("item_removed",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (StuffKeeperDataBackendClass, item_removed),
			NULL, NULL,
			___marshal_Sig2,
			G_TYPE_NONE, 1,
			G_TYPE_INT);
	if ___GOB_UNLIKELY(sizeof(gint ) != sizeof(gint ) || parent_class == NULL /* avoid warning */) {
		g_error("stuffkeeper-data-backend.gob line 33: Type mismatch of \"item_removed\" signal signature");
	}

#line 18 "stuffkeeper-data-backend.gob"
	c->item_changed = ___real_stuffkeeper_data_backend_item_changed;
#line 25 "stuffkeeper-data-backend.gob"
	c->item_added = ___real_stuffkeeper_data_backend_item_added;
#line 33 "stuffkeeper-data-backend.gob"
	c->item_removed = ___real_stuffkeeper_data_backend_item_removed;
#line 129 "stuffkeeper-data-backend.gob"
	g_object_class->finalize = ___finalize;
#line 266 "stuffkeeper-data-backend.c"
}
#undef __GOB_FUNCTION__



#line 18 "stuffkeeper-data-backend.gob"
void 
stuffkeeper_data_backend_item_changed (StuffKeeperDataBackend * self, StuffKeeperDataItem * item)
#line 275 "stuffkeeper-data-backend.c"
{
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 18 "stuffkeeper-data-backend.gob"
	g_return_if_fail (self != NULL);
#line 18 "stuffkeeper-data-backend.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_BACKEND (self));
#line 287 "stuffkeeper-data-backend.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) item);

	g_signal_emitv (___param_values,
		object_signals[ITEM_CHANGED_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
}
#line 18 "stuffkeeper-data-backend.gob"
static void 
___real_stuffkeeper_data_backend_item_changed (StuffKeeperDataBackend * self G_GNUC_UNUSED, StuffKeeperDataItem * item)
#line 308 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::item_changed"
{
#line 21 "stuffkeeper-data-backend.gob"
	
        printf("Item changed\n");
    }}
#line 316 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__

#line 25 "stuffkeeper-data-backend.gob"
void 
stuffkeeper_data_backend_item_added (StuffKeeperDataBackend * self, StuffKeeperDataItem * item)
#line 322 "stuffkeeper-data-backend.c"
{
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 25 "stuffkeeper-data-backend.gob"
	g_return_if_fail (self != NULL);
#line 25 "stuffkeeper-data-backend.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_BACKEND (self));
#line 334 "stuffkeeper-data-backend.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) item);

	g_signal_emitv (___param_values,
		object_signals[ITEM_ADDED_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
}
#line 25 "stuffkeeper-data-backend.gob"
static void 
___real_stuffkeeper_data_backend_item_added (StuffKeeperDataBackend * self G_GNUC_UNUSED, StuffKeeperDataItem * item)
#line 355 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::item_added"
{
#line 28 "stuffkeeper-data-backend.gob"
	
        printf("Item added signal: '%i'\n", stuffkeeper_data_item_get_id(item));
        g_signal_connect_swapped(G_OBJECT(item), "item-changed", G_CALLBACK(self_item_changed), self);

    }}
#line 365 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__

#line 33 "stuffkeeper-data-backend.gob"
void 
stuffkeeper_data_backend_item_removed (StuffKeeperDataBackend * self, gint id)
#line 371 "stuffkeeper-data-backend.c"
{
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 33 "stuffkeeper-data-backend.gob"
	g_return_if_fail (self != NULL);
#line 33 "stuffkeeper-data-backend.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_BACKEND (self));
#line 383 "stuffkeeper-data-backend.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_INT);
	g_value_set_int (&___param_values[1], (gint ) id);

	g_signal_emitv (___param_values,
		object_signals[ITEM_REMOVED_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
}
#line 33 "stuffkeeper-data-backend.gob"
static void 
___real_stuffkeeper_data_backend_item_removed (StuffKeeperDataBackend * self G_GNUC_UNUSED, gint id)
#line 404 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::item_removed"
{
#line 36 "stuffkeeper-data-backend.gob"
	
        printf("Item removed signal: '%i'\n",id); 
    }}
#line 412 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__

#line 43 "stuffkeeper-data-backend.gob"
StuffKeeperDataItem * 
stuffkeeper_data_backend_get_item (StuffKeeperDataBackend * self, gint id)
#line 418 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::get_item"
#line 43 "stuffkeeper-data-backend.gob"
	g_return_val_if_fail (self != NULL, (StuffKeeperDataItem * )0);
#line 43 "stuffkeeper-data-backend.gob"
	g_return_val_if_fail (STUFFKEEPER_IS_DATA_BACKEND (self), (StuffKeeperDataItem * )0);
#line 425 "stuffkeeper-data-backend.c"
{
#line 46 "stuffkeeper-data-backend.gob"
	
        StuffKeeperDataItem *item;
        item = g_hash_table_lookup(self->_priv->items, &id);
        return item;
    }}
#line 433 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__

#line 52 "stuffkeeper-data-backend.gob"
StuffKeeperDataItem * 
stuffkeeper_data_backend_new_item (StuffKeeperDataBackend * self)
#line 439 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::new_item"
#line 52 "stuffkeeper-data-backend.gob"
	g_return_val_if_fail (self != NULL, (StuffKeeperDataItem * )0);
#line 52 "stuffkeeper-data-backend.gob"
	g_return_val_if_fail (STUFFKEEPER_IS_DATA_BACKEND (self), (StuffKeeperDataItem * )0);
#line 446 "stuffkeeper-data-backend.c"
{
#line 55 "stuffkeeper-data-backend.gob"
	
        gint *id;
        StuffKeeperDataItem *item;
        /* create a new item */
        item = stuffkeeper_data_item_new("/home/qball/.stuffkeeper/items/");
        /* want to copy the key, even if it is an integer */
        id = g_malloc0(sizeof(gint));
        *id = stuffkeeper_data_item_get_id(item);
        /* insert it into my hash-list */
        g_hash_table_insert(self->_priv->items,id, item);
        self_item_added(self, item);

        return item;
    }}
#line 463 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__

#line 70 "stuffkeeper-data-backend.gob"
void 
stuffkeeper_data_backend_remove_item (StuffKeeperDataBackend * self, gint id)
#line 469 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::remove_item"
#line 70 "stuffkeeper-data-backend.gob"
	g_return_if_fail (self != NULL);
#line 70 "stuffkeeper-data-backend.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_BACKEND (self));
#line 476 "stuffkeeper-data-backend.c"
{
#line 73 "stuffkeeper-data-backend.gob"
	
        StuffKeeperDataItem *item = g_hash_table_lookup(self->_priv->items, &id);
        if(item)
        {
            stuffkeeper_data_item_delete_yourself(item); 
        }
        if(g_hash_table_remove(self->_priv->items, &id) == FALSE)
        {
            printf("failed to remove: %i\n", id);
            return;
        }
        self_item_removed(self, id);
    }}
#line 492 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__

#line 88 "stuffkeeper-data-backend.gob"
void 
stuffkeeper_data_backend_load (StuffKeeperDataBackend * self)
#line 498 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::load"
#line 88 "stuffkeeper-data-backend.gob"
	g_return_if_fail (self != NULL);
#line 88 "stuffkeeper-data-backend.gob"
	g_return_if_fail (STUFFKEEPER_IS_DATA_BACKEND (self));
#line 505 "stuffkeeper-data-backend.c"
{
#line 91 "stuffkeeper-data-backend.gob"
	
        StuffKeeperDataItem *item;
        printf("Loading content\n");

        /* Load schema's */
        GDir *dir = g_dir_open("/home/qball/.stuffkeeper/items", 0, NULL);
        if(dir)
        {
            gchar *filename;
            while((filename = g_dir_read_name(dir))!= NULL)
            {
                gchar *full_path = g_strdup_printf("/home/qball/.stuffkeeper/items/%s", filename);
                StuffKeeperDataItem *item;
                gint *id;
                /* create a new item */
                item = stuffkeeper_data_item_new_from_file(full_path);
                /* want to copy the key, even if it is an integer */
                id = g_malloc0(sizeof(gint));
                *id = stuffkeeper_data_item_get_id(item);
                /* insert it into my hash-list */
                g_hash_table_insert(self->_priv->items,id, item);
                self_item_added(self, item);

                g_free(full_path);
            }
            g_dir_close(dir);
        }
        /* Load items */
    }}
#line 537 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__

#line 121 "stuffkeeper-data-backend.gob"
static void 
stuffkeeper_data_backend_finalize_item (gint * key, StuffKeeperDataItem * item, gpointer user_data)
#line 543 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::finalize_item"
{
#line 124 "stuffkeeper-data-backend.gob"
	
        stuffkeeper_data_item_save_yourself(item);
    }}
#line 551 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__

#line 129 "stuffkeeper-data-backend.gob"
static void 
___9_stuffkeeper_data_backend_finalize (GObject * obj G_GNUC_UNUSED)
#line 557 "stuffkeeper-data-backend.c"
#define PARENT_HANDLER(___obj) \
	{ if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(___obj); }
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::finalize"
{
#line 132 "stuffkeeper-data-backend.gob"
	
        Self *self = SELF(obj);
        printf("destroying\n");

        if(self->_priv->items)
        {
            g_hash_table_foreach(self->_priv->items, (GHFunc)self_finalize_item, NULL);
            g_hash_table_destroy(self->_priv->items);

            self->_priv->items = NULL;
        }

            PARENT_HANDLER(obj);
    }}
#line 579 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 149 "stuffkeeper-data-backend.gob"
StuffKeeperDataBackend * 
stuffkeeper_data_backend_new (void)
#line 586 "stuffkeeper-data-backend.c"
{
#define __GOB_FUNCTION__ "StuffKeeper:Data:Backend::new"
{
#line 152 "stuffkeeper-data-backend.gob"
	
            printf("Creating backend\n");
            return GET_NEW;
        }}
#line 595 "stuffkeeper-data-backend.c"
#undef __GOB_FUNCTION__
