/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __STUFFKEEPER_DATA_BACKEND_PRIVATE_H__
#define __STUFFKEEPER_DATA_BACKEND_PRIVATE_H__

#include "stuffkeeper-data-backend.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _StuffKeeperDataBackendPrivate {
#line 18 "stuffkeeper-data-backend.gob"
	GHashTable * tags;
#line 21 "stuffkeeper-data-backend.gob"
	GHashTable * items;
#line 24 "stuffkeeper-data-backend.gob"
	gchar * path;
#line 20 "stuffkeeper-data-backend-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
