/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __STUFFKEEPER_DATA_TAG_PRIVATE_H__
#define __STUFFKEEPER_DATA_TAG_PRIVATE_H__

#include "stuffkeeper-data-tag.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 3 "stuffkeeper-data-tag.gob"

#include <stdio.h>
#define KEYFILE_GENERAL "general"


#line 20 "stuffkeeper-data-tag-private.h"
struct _StuffKeeperDataTagPrivate {
#line 11 "stuffkeeper-data-tag.gob"
	GKeyFile * data;
#line 12 "stuffkeeper-data-tag.gob"
	char * path;
#line 26 "stuffkeeper-data-tag-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
