#! /usr/bin/env python
# encoding: utf-8
# Qball Cow, 2008

#install_files('PACKAGE_DATADIR', '', 'stuffkeeper.glade')

obj = bld.create_obj('cc', 'program')
obj.find_sources_in_dirs('.') # take the sources in the current folder
#obj.packages = 'gtk+-2.0'
obj.target = 'stuffkeeper'
obj.uselib = 'GTK GLIB GLADE GMODULE GTKSPELL SQLITE'
obj.includes='.'

